### ISSUE TITLE
[HLE Bios] Nuclear Strike, Ape Escape... Issues with card_info

### ISSUE THREAD

**Issue by gameblabla** [gameblabla/pcsx4all#8]
Nuclear Strike works generally fine on PCSX4ALL with HLE bios except for one glaring flaw :  
it does not detect memory cards. And when the code is "fixed" for that, it crashes horribly.

An issue on PCSX4ALL has been opened about this and here's what they had to say

>Nuclear Strike does not save or load memory. It says no card detected. If you remove
the // from // from DeliverEvent(0x11, 0x2); /* 0xf0000011, 0x0004 */ in card_info the
game segfaults when trying to load game. This the back trace.
Program received signal SIGSEGV, Segmentation fault.
0x000000000044ba71 in psxBios__card_info () at psxbios.c:1275
1275 void psxBios__card_info() { // ab
(gdb) bt
0#0 0x000000000044ba71 in psxBios__card_info () at psxbios.c:1275
1#1 0x000000000042dd7c in hleA0 () at psxhle.c:35
2#2 0x00007fffebd09950 in ?? ()
3#3 0x0000000000000000 in ?? ()

One of the devs said : 
> This game creates a callback and handles memory card reading state machine thru those callbacks.
Now on HLE BIOS level this means lots recursion, and since every HLE BIOS calls allocated stack frame it overflows at some point.
Notice below the number increasing after card_info which signifies recursed call number within hleSoftCall
000000a4 2eaf37b5: psxBios__card_info: 0x0 __1__000000a4 2eaf37b5: psxBios_DeliverEvent 81 2 2000 1000000000a4 2eaf3801: psxBios__card_load: 0000000a4 2eaf3801: psxBios_DeliverEvent 81 2 2000 1000000000b4 2eaf3867: psxBios__card_read000000b4 2eaf3867: psxBios_DeliverEvent 81 2 2000 1000000000a4 2eaf38ee: psxBios__card_info: 0x0 2000000a4 2eaf38ee: psxBios_DeliverEvent 81 2 2000 1000000000a4 2eaf3975: psxBios__card_info: 0x0 3000000a4 2eaf3975: psxBios_DeliverEvent 81 2 2000 1000000000a4 2eaf39fc: psxBios__card_info: 0x0 4000000a4 2eaf39fc: psxBios_DeliverEvent 81 2 2000 1000.......000000a4 2f28f744: psxBios_DeliverEvent 81 2 2000 1000000000a4 2f28f7cb: psxBios__card_info: 0x0 58019000000a4 2f28f7cb: psxBios_DeliverEvent 81 2 2000 1000000000a4 2f28f852: psxBios__card_info: 0x0 __58020__000000a4 2f28f852: psxBios_DeliverEvent 81 2 2000 1000
I am not sure how to handle these situations. Maybe either these
a) Fake call chain somehow, but how?b) Create BIOS functions which don't allocate stack frame each time

Removing DeliverEvent(0x11, 0x2); in card_info does indeed make the call recursively call the function.
It does this more than 4000+ times before stack is overrun and the game crashes.

How would i go fixing this is beyond me... But that still doesn't prevent the game from being playable with save states still, which i would recommend for now.

**Comment by gameblabla** [comment]
Games that apparently suffers from this issue too are Ape Escape, Ridge Racer Type 4 and Grand Turismo.
According to another bug report from a developer : 
> This game has the same fundamental issue like Nuclear Strike that the game code jumps back to BIOS execution after callback and since HLE BIOS doesn't have any delays or so, then excess card_info calls cause dead locking.
I am not going to fix this or Nuclear Strike anytime soon since it requires lots of work and I don't have any ideas how to fix this elegantly without adding those poor delays to HLE BIOS which made official Sony BIOS so poor in performance.

I guess it could be fixed by adding those "said" delays ? (i think he means increasing the cpu cycle)
**EDIT**: If he meant CPU cycles, then that's definitely not the way it should be fixed because most, if not all BIOS functions with official bios, do not seem to directly increase the CPU cycle count.
However, HLE & LLE Bios are still different in this regard.... so i do not know what to think about it.
I do think there should be a fix for the recursion issue though.
